name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4' # Of een andere PHP versie die je gebruikt

    - name: Install dependencies
      run: composer install

    - name: Make PHPUnit executable
      run: chmod +x vendor/bin/phpunit

    - name: Run tests
      run: vendor/bin/phpunit --configuration phpunit.xml
